name: Build plugin

on: [push, pull_request]

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build with maven
        working-directory: ./TrustedTravelPlugin
        run: mvn package
      - name: capture build artifacts
        if: ${{ matrix.java == '21' }} # Only upload artifacts built from latest java
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: TrustedTravelPlugin/target/